import type { PortfolioVisualLabels } from "./types";

export const englishVisualLabels = {
  sceneFallback: {
    title: "Interactive 3D preview unavailable",
    description: "This 3D environment requires WebGL to run.",
  },
  controllerRuntime: {
    realTimeController: "real-time robot controller",
    agenticWorkflow: "agentic workflow",
    agentInterface: "agent interface",
    taskManager: "task manager",
    tasks: ["task 01", "task 02", "task 03", "task 04"],
    robotHardware: "robot hardware",
  },
  gpuPlatform: {
    deploymentPlatform: "deployment platform",
    llmServing: "LLM serving",
    simulation: "Simulation",
    monitoring: "Monitoring",
    kubernetesCluster: "Kubernetes cluster",
    deploymentStatus: "deployment status",
    clusterHealthy: "cluster healthy",
    deployment: "deployment",
    replicas: "ready replicas",
    status: "status",
    ready: "ready",
    deploying: "deploying",
  },
  edgeLlm: {
    onDevice: "on-device",
    edge: "EDGE",
    inference: "inference",
  },
  mcp: {
    cppApplication: "C++ application",
    nativeRuntime: "native runtime",
    robotApi: "robot API",
    planner: "planner",
    telemetry: "telemetry",
    typedCalls: "typed calls",
    tools: "tools",
    resources: "resources",
    agent: "Agent",
  },
  topic: {
    containerResources: "container resources",
    relativeToLimits: "usage relative to runtime limits",
    cpu: "CPU",
    memory: "memory",
    gpu: "GPU",
    cgroupLimit: "cgroup limit",
  },
  leetcode: {
    problem: "Problem",
    description: "description",
    examples: "examples",
    accepted: "Accepted",
    pythonScraper: "Python scraper",
    gitRepository: "Git repository",
  },
  kims: {
    vectorizedEnvironments: "vectorized environments",
  },
} satisfies PortfolioVisualLabels;

export const koreanVisualLabels = {
  sceneFallback: {
    title: "인터랙티브 3D 미리보기를 사용할 수 없습니다",
    description: "이 3D 환경을 실행하려면 WebGL이 필요합니다.",
  },
  controllerRuntime: {
    realTimeController: "실시간 로봇 컨트롤러",
    agenticWorkflow: "에이전틱 워크플로",
    agentInterface: "에이전트 인터페이스",
    taskManager: "태스크 관리자",
    tasks: ["태스크 01", "태스크 02", "태스크 03", "태스크 04"],
    robotHardware: "로봇 하드웨어",
  },
  gpuPlatform: {
    deploymentPlatform: "배포 플랫폼",
    llmServing: "LLM 서빙",
    simulation: "시뮬레이션",
    monitoring: "모니터링",
    kubernetesCluster: "Kubernetes 클러스터",
    deploymentStatus: "배포 상태",
    clusterHealthy: "클러스터 정상",
    deployment: "배포",
    replicas: "준비된 레플리카",
    status: "상태",
    ready: "준비 완료",
    deploying: "배포 중",
  },
  edgeLlm: {
    onDevice: "온디바이스",
    edge: "EDGE",
    inference: "추론",
  },
  mcp: {
    cppApplication: "C++ 애플리케이션",
    nativeRuntime: "네이티브 런타임",
    robotApi: "로봇 API",
    planner: "플래너",
    telemetry: "텔레메트리",
    typedCalls: "타입 기반 호출",
    tools: "도구",
    resources: "리소스",
    agent: "에이전트",
  },
  topic: {
    containerResources: "컨테이너 리소스",
    relativeToLimits: "런타임 제한 대비 사용량",
    cpu: "CPU",
    memory: "메모리",
    gpu: "GPU",
    cgroupLimit: "cgroup 제한",
  },
  leetcode: {
    problem: "문제",
    description: "문제 설명",
    examples: "예제",
    accepted: "통과",
    pythonScraper: "Python 스크레이퍼",
    gitRepository: "Git 리포지토리",
  },
  kims: {
    vectorizedEnvironments: "벡터화 환경",
  },
} satisfies PortfolioVisualLabels;

export const brazilianPortugueseVisualLabels = {
  sceneFallback: {
    title: "Prévia 3D interativa indisponível",
    description: "Este ambiente 3D requer WebGL para funcionar.",
  },
  controllerRuntime: {
    realTimeController: "controlador do robô em tempo real",
    agenticWorkflow: "fluxo de trabalho agêntico",
    agentInterface: "interface para agentes",
    taskManager: "gerenciador de tarefas",
    tasks: ["tarefa 01", "tarefa 02", "tarefa 03", "tarefa 04"],
    robotHardware: "hardware do robô",
  },
  gpuPlatform: {
    deploymentPlatform: "plataforma de implantação",
    llmServing: "inferência de LLMs",
    simulation: "Simulação",
    monitoring: "Monitoramento",
    kubernetesCluster: "cluster Kubernetes",
    deploymentStatus: "estado das implantações",
    clusterHealthy: "cluster saudável",
    deployment: "implantação",
    replicas: "réplicas prontas",
    status: "estado",
    ready: "pronta",
    deploying: "implantando",
  },
  edgeLlm: {
    onDevice: "no dispositivo",
    edge: "EDGE",
    inference: "inferência",
  },
  mcp: {
    cppApplication: "aplicação C++",
    nativeRuntime: "runtime nativo",
    robotApi: "API do robô",
    planner: "planejador",
    telemetry: "telemetria",
    typedCalls: "chamadas tipadas",
    tools: "ferramentas",
    resources: "recursos",
    agent: "Agente",
  },
  topic: {
    containerResources: "recursos do contêiner",
    relativeToLimits: "uso relativo aos limites de execução",
    cpu: "CPU",
    memory: "memória",
    gpu: "GPU",
    cgroupLimit: "limite do cgroup",
  },
  leetcode: {
    problem: "Problema",
    description: "descrição",
    examples: "exemplos",
    accepted: "Aceita",
    pythonScraper: "scraper em Python",
    gitRepository: "repositório Git",
  },
  kims: {
    vectorizedEnvironments: "ambientes vetorizados",
  },
} satisfies PortfolioVisualLabels;
