import type { PortfolioVisualLabels } from "./types";

export const englishVisualLabels = {
  sceneFallback: {
    title: "Interactive 3D preview unavailable",
    description: "This 3D environment requires WebGL to run.",
  },
  controllerRuntime: {
    realTimeController: "real-time controller",
    taskManagement: "task management",
    dataFlow: "data flow",
    agent: "agent",
    agentInterface: "agent interface",
    agenticWorkflows: "agentic workflows",
    tasks: ["task 01", "task 02", "task 03", "task 04"],
    realRobot: "real robot",
  },
  gpuPlatform: {
    deploymentPlatform: "deployment platform",
    llmEnvironment: "LLM environment",
    simulation: "Simulation",
    metrics: "Metrics",
    deploy: "deploy",
    monitor: "monitor",
    kubernetesCluster: "Kubernetes cluster",
    healthy: "healthy",
    llmAbbreviation: "LLM",
    simulationAbbreviation: "SIM",
    metricsAbbreviation: "METRICS",
  },
  edgeLlm: {
    onDevice: "on-device",
    edge: "EDGE",
    inference: "inference",
  },
  mcp: {
    cppApplication: "C++ application",
    nativeRuntime: "native runtime",
    robotApi: "robot API",
    planner: "planner",
    telemetry: "telemetry",
    typedCalls: "typed calls",
    tools: "tools",
    resources: "resources",
    agent: "Agent",
  },
  leetcode: {
    problem: "Problem 0042",
    description: "description",
    examples: "examples",
    accepted: "Accepted",
    pythonScraper: "Python scraper",
    gitRepository: "Git repository",
  },
  kims: {
    vectorizedEnvironments: "vectorized environments",
    policy: "policy",
    rollouts: "rollouts",
    reward: "reward",
  },
} satisfies PortfolioVisualLabels;

export const koreanVisualLabels = {
  sceneFallback: {
    title: "인터랙티브 3D 미리보기를 사용할 수 없습니다",
    description: "이 3D 환경을 실행하려면 WebGL이 필요합니다.",
  },
  controllerRuntime: {
    realTimeController: "실시간 컨트롤러",
    taskManagement: "태스크 관리",
    dataFlow: "데이터 흐름",
    agent: "에이전트",
    agentInterface: "에이전트 인터페이스",
    agenticWorkflows: "에이전틱 워크플로",
    tasks: ["태스크 01", "태스크 02", "태스크 03", "태스크 04"],
    realRobot: "실제 로봇",
  },
  gpuPlatform: {
    deploymentPlatform: "배포 플랫폼",
    llmEnvironment: "LLM 환경",
    simulation: "시뮬레이션",
    metrics: "메트릭",
    deploy: "배포",
    monitor: "모니터링",
    kubernetesCluster: "Kubernetes 클러스터",
    healthy: "정상",
    llmAbbreviation: "LLM",
    simulationAbbreviation: "SIM",
    metricsAbbreviation: "METRICS",
  },
  edgeLlm: {
    onDevice: "온디바이스",
    edge: "EDGE",
    inference: "추론",
  },
  mcp: {
    cppApplication: "C++ 애플리케이션",
    nativeRuntime: "네이티브 런타임",
    robotApi: "로봇 API",
    planner: "플래너",
    telemetry: "텔레메트리",
    typedCalls: "타입 기반 호출",
    tools: "도구",
    resources: "리소스",
    agent: "에이전트",
  },
  leetcode: {
    problem: "문제 0042",
    description: "문제 설명",
    examples: "예제",
    accepted: "정답",
    pythonScraper: "Python 스크레이퍼",
    gitRepository: "Git 리포지토리",
  },
  kims: {
    vectorizedEnvironments: "벡터화 환경",
    policy: "정책",
    rollouts: "롤아웃",
    reward: "보상",
  },
} satisfies PortfolioVisualLabels;
